# Generated by Django 3.2.6 on 2021-08-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='Description',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='Image',
            field=models.ImageField(default=1, upload_to='static/uploads/country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='Name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
