# Generated by Django 3.2.6 on 2021-08-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20210828_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='accommodation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='durations',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='extra',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
