# Generated by Django 3.2.5 on 2021-08-24 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20210824_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='Upload_Image',
            new_name='Image',
        ),
    ]
