# Generated by Django 3.2.6 on 2021-08-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20210828_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='continents',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='day_one',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='day_three',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='day_two',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='dest_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='dest_image',
            field=models.ImageField(default=1, upload_to='static/uploads/destination'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='dest_location',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='dest_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='dest_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
