# Generated by Django 3.2.6 on 2021-08-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_auto_20210828_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='offer',
        ),
    ]
