# Generated by Django 3.2.6 on 2021-08-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_remove_place_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admins.offer'),
            preserve_default=False,
        ),
    ]
