# Generated by Django 3.2.6 on 2021-08-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_remove_place_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
    ]
