# Generated by Django 3.2.6 on 2021-08-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_remove_place_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admins.country'),
            preserve_default=False,
        ),
    ]
