# Generated by Django 3.2.6 on 2021-08-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_place_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='continents',
        ),
    ]
