# Generated by Django 3.2.6 on 2021-09-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_remove_place_continents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='dest_image',
            field=models.ImageField(default='static/images/profile.gif', upload_to='static/uploads/destination'),
        ),
    ]
