# Generated by Django 3.2.6 on 2021-09-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_alter_place_dest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='Number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
