# Generated by Django 3.2.6 on 2021-09-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_alter_place_dest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='video_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
