# Generated by Django 3.2.6 on 2021-09-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0019_rename_video_url_country_bg_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='total_person',
            field=models.IntegerField(default=2, max_length=10),
        ),
    ]
