# Generated by Django 3.2.6 on 2021-09-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0020_place_total_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='dest_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='total_person',
            field=models.IntegerField(default=2),
        ),
    ]
