# Generated by Django 3.2.6 on 2021-09-24 02:37

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0021_auto_20210910_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='day_three',
        ),
        migrations.AlterField(
            model_name='country',
            name='Description',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(30)]),
        ),
        migrations.AlterField(
            model_name='country',
            name='Name',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='country',
            name='Number',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')]),
        ),
        migrations.AlterField(
            model_name='country',
            name='bg_url',
            field=models.URLField(validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='extra',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='place',
            name='day_one',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='place',
            name='day_two',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='place',
            name='dest_desc',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='place',
            name='dest_image',
            field=models.ImageField(upload_to='static/uploads/destination', validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='place',
            name='dest_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='place',
            name='dest_price',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')]),
        ),
        migrations.AlterField(
            model_name='place',
            name='dest_type',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
