# Generated by Django 3.2.6 on 2021-09-25 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0022_auto_20210924_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='day_three',
            field=models.TextField(default=1, validators=[django.core.validators.MaxLengthValidator(1000)]),
            preserve_default=False,
        ),
    ]
