# Generated by Django 3.2.6 on 2021-09-25 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0023_place_day_three'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='Name',
            field=models.CharField(db_index=True, max_length=120, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='place',
            name='dest_name',
            field=models.CharField(db_index=True, max_length=50, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
