# Generated by Django 3.2.5 on 2021-08-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_category_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=100)),
                ('accommodation', models.CharField(max_length=100)),
                ('extra', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(upload_to='category_img/'),
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='place_img/')),
                ('desc', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.offers')),
            ],
        ),
    ]
