# Generated by Django 3.2.5 on 2021-08-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210823_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='desc',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
