# Generated by Django 3.2.5 on 2021-08-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_country_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='desc',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
