# Generated by Django 3.2.6 on 2021-09-01 16:03

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ecard',
        ),
        migrations.AddField(
            model_name='profile',
            name='ecard_cvv',
            field=models.CharField(default=dashboard.models.random_cvv, max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='ecard_no',
            field=models.CharField(default=dashboard.models.random_ecard, max_length=16),
        ),
    ]
