# Generated by Django 3.2.6 on 2021-09-06 10:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_country_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0016_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_person', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('total_price', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('In-Review', 'In-Review'), ('Confirmed', 'Confirmend')], max_length=200, null=True)),
                ('contact_no', models.CharField(max_length=10, null=True)),
                ('booked_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.place')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
