# Generated by Django 3.2.6 on 2021-09-06 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_country_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0017_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
