# Generated by Django 3.2.6 on 2021-09-06 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_country_video_url'),
        ('dashboard', '0018_booking_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_draft',
            name='country',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='admins.country'),
            preserve_default=False,
        ),
    ]
