# Generated by Django 3.2.6 on 2021-09-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_booking_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_draft',
            name='total_person',
            field=models.IntegerField(default=2),
        ),
    ]
