# Generated by Django 3.2.6 on 2021-09-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_booking_draft_total_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='contact_no',
        ),
    ]
