# Generated by Django 3.2.6 on 2021-09-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_booking_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='static/images/prof.png', upload_to='static/uploads/profile'),
        ),
    ]
