# Generated by Django 3.2.6 on 2021-09-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='person',
            field=models.IntegerField(default=1),
        ),
    ]
