# Generated by Django 3.2.6 on 2021-09-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20210916_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('In-Review', 'In-Review'), ('Confirmed', 'Confirmed')], max_length=200, null=True),
        ),
    ]
