# Generated by Django 3.2.5 on 2021-08-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Country',
        ),
    ]
