# Generated by Django 3.2.6 on 2021-09-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20210908_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
