# Generated by Django 3.2.5 on 2021-08-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_country_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='desc',
        ),
    ]
