# Generated by Django 3.2.5 on 2021-08-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_country_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
